# Generated by Django 4.0.4 on 2022-04-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='on_going',
            new_name='status',
        ),
    ]
